### ISSUE TITLE
Here's a build I did so you don't have to.

### ISSUE THREAD

**Issue by ChildishGiant** [Ploaj/CrossMod#10]
'tis all I came here to ask.

**Comment by ChildishGiant** [comment]
I've managed to build, I'm assuming it's cool for me to post it here for other people?

**Comment by ChildishGiant** [comment]
I've uploaded it here, since github file upload seems dead, as does mega's 
https://drive.google.com/open?id=1cgOD0XT6UXdleKFuyJxa3sdebL2pKe2H

**Comment by ScanMountGoat** [comment]
Issues are designed for bugs or feature requests.
