### ISSUE TITLE
Render seems to render the background and textures can't be exported

### ISSUE THREAD

**Issue by trainboy2019** [Ploaj/CrossMod#11]
When rendering a model, the background seems to be rendered with it. If this is intentional, could an option be added to render without a background? And for textures, I can't seem to save them as png or anything.

**Comment by ScanMountGoat** [comment]
There always has to be a background. Right click the nutexb nodes to export.

**Comment by trainboy2019** [comment]
Ah, I see textures were added recently.
Why does there always have to be a background? And if that's the case, why not set it's alpha channel to zero when rendering?

**Comment by ScanMountGoat** [comment]
There's always something in the background. We aren't supporting exporting transparent screenshots anytime soon.
