### ISSUE TITLE
Exporting to dae generates unhandled exception, smd export creates corrupt model

### ISSUE THREAD

**Issue by BSoD38** [Ploaj/CrossMod#8]
I've tried exporting two different characters : Inceneroar (gaogaen) and Corrin (kamui).

Exporting a model to dae generates the following unhandled exception :
```
>	CrossMod.exe!CrossMod.IO.IO_DAE.ExportIOModelAsDAE(string FileName, CrossMod.IO.IOModel m) Line 299
System.Collections.Generic.KeyNotFoundException : 'La clé donnée était absente du dictionnaire.'
```
The french part translates into "The given key didn't exist in the dictionary".

Exporting a model to smd seems to work fine, but I get the following error when importing into blender using Source Tools : 

![blender](https://i.imgur.com/9hAn9gM.png)

I might be doing something wrong, but I can't export models (with UVs and rigging) because of that.

**Comment by Ploaj** [comment]
I set the culture to invariant which should hopefully fix the smd issue.
The DAE issue is now fixed as well.
